### PR TITLE
Bounding boxes drawn in browser; magnifier on hover

### PR DESCRIPTION
**Pull request by jnothman**
This is something else I cooked up over a few weeks as a way to get interactivity when mousing over an image, but without creating a full-blown image details popup.

Wdyt, @geezacoleman?
Screen recording of hovering result cards

### CODE REVIEW

**Comment by geezacoleman** [comment]
> This is something else I cooked up over a few weeks as a way to get interactivity when mousing over an image, but without creating a full-blown image details popup.
> 
> Wdyt, @geezacoleman?

That looks quite nice! tbh while I imagine the full image pop up is more expected, this provides better functionality for inspecting individual weeds/pixels/blur.

**Comment by jnothman** [comment]
Yeah I also think the full pop up would be nice. Do you think we should keep this half-baked design?

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by geezacoleman** [comment]
I think keep it as is for now - I quite like it. I've already used it to check out the annotations further. Seems to work fairly consistently.

**Comment by jnothman** [comment]
Any big issues with the code here, @ElevnLi?

**Comment by ElevnLi** [comment]
> Any big issues with the code here, @ElevnLi?

LGTM, this is really cool

**Pull request merged**
