### PR TITLE
Hover card with species detail

### PR DESCRIPTION
**Pull request by jnothman**
I wanted have a go with the GBIF species API, so I made this hover card showing taxonomy and vernacular name.

image
image

Useful, @geezacoleman?

### CODE REVIEW

**Comment by geezacoleman** [comment]
Looks neat! Although the common name *ball-turnip* seems to be something different altogether?

**Comment by jnothman** [comment]
Curious GBIF insists that's its name. Ideally vernacular names come from WSSA?? Okay to deploy without that change?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jnothman** [comment]
hmmm you make me wonder if it's actually a bug.

**Comment by jnothman** [comment]
Very strange. Here's what https://api.gbif.org/v1/species?name=rapistrum+rugosum&datasetKey=d7dddbf4-2cf0-4f39-9b2a-bb099caae36c&taxonomicStatus=ACCEPTED returns:
```json
{
  "offset": 0,
  "limit": 20,
  "endOfRecords": true,
  "results": [
    {
      "key": 5373368,
      "nubKey": 5373368,
      "nameKey": 9674266,
      "taxonID": "gbif:5373368",
      "sourceTaxonKey": 171678401,
      "kingdom": "Plantae",
      "phylum": "Tracheophyta",
      "order": "Brassicales",
      "family": "Brassicaceae",
      "genus": "Rapistrum",
      "species": "Rapistrum rugosum",
      "kingdomKey": 6,
      "phylumKey": 7707728,
      "classKey": 220,
      "orderKey": 7225535,
      "familyKey": 3112,
      "genusKey": 8306649,
      "speciesKey": 5373368,
      "datasetKey": "d7dddbf4-2cf0-4f39-9b2a-bb099caae36c",
      "constituentKey": "7ddf754f-d193-4cc9-b351-99906754a03b",
      "parentKey": 8306649,
      "parent": "Rapistrum",
      "scientificName": "Rapistrum rugosum (L.) All.",
      "canonicalName": "Rapistrum rugosum",
      "vernacularName": "ball-turnip",
      "authorship": "All. (L.)",
      "nameType": "SCIENTIFIC",
      "rank": "SPECIES",
      "origin": "SOURCE",
      "taxonomicStatus": "ACCEPTED",
      "nomenclaturalStatus": [],
      "remarks": "",
      "publishedIn": "Fl. pedem. 1:257.  1785",
      "numDescendants": 2,
      "lastCrawled": "2021-03-03T06:32:33.335+0000",
      "lastInterpreted": "2021-03-03T06:23:02.509+0000",
      "issues": [],
      "synonym": false,
      "class": "Magnoliopsida"
    },
    {
      "key": 8418051,
      "nameKey": 38555179,
      "taxonID": "gbif:8418051",
      "sourceTaxonKey": 161220503,
      "kingdom": "Plantae",
      "phylum": "Tracheophyta",
      "order": "Brassicales",
      "family": "Brassicaceae",
      "genus": "Rapistrum",
      "species": "Rapistrum rugosum",
      "kingdomKey": 6,
      "phylumKey": 7707728,
      "classKey": 220,
      "orderKey": 7225535,
      "familyKey": 3112,
      "genusKey": 8306649,
      "speciesKey": 5373368,
      "datasetKey": "d7dddbf4-2cf0-4f39-9b2a-bb099caae36c",
      "constituentKey": "0e61f8fe-7d25-4f81-ada7-d970bbb2c6d6",
      "parentKey": 8306649,
      "parent": "Rapistrum",
      "acceptedKey": 5373368,
      "accepted": "Rapistrum rugosum (L.) All.",
      "basionymKey": 3040878,
      "basionym": "Myagrum rugosum L.",
      "scientificName": "Rapistrum rugosum (L.) J.P.Bergeret, 1786",
      "canonicalName": "Rapistrum rugosum",
      "vernacularName": "bastard cabbage",
      "authorship": "J.P.Bergeret, 1786 (L.)",
      "nameType": "SCIENTIFIC",
      "rank": "SPECIES",
      "origin": "SOURCE",
      "taxonomicStatus": "SYNONYM",
      "nomenclaturalStatus": [],
      "remarks": "",
      "numDescendants": 0,
      "lastCrawled": "2021-03-03T06:32:33.335+0000",
      "lastInterpreted": "2021-03-03T06:23:02.550+0000",
      "issues": [
        "ORIGINAL_NAME_DERIVED"
      ],
      "synonym": true,
      "class": "Magnoliopsida"
    },
    {
      "key": 10924593,
      "nameKey": 41084738,
      "taxonID": "gbif:10924593",
      "sourceTaxonKey": 164011227,
      "kingdom": "Plantae",
      "phylum": "Tracheophyta",
      "order": "Brassicales",
      "family": "Brassicaceae",
      "genus": "Rapistrum",
      "species": "Rapistrum rugosum",
      "kingdomKey": 6,
      "phylumKey": 7707728,
      "classKey": 220,
      "orderKey": 7225535,
      "familyKey": 3112,
      "genusKey": 8306649,
      "speciesKey": 10924593,
      "datasetKey": "d7dddbf4-2cf0-4f39-9b2a-bb099caae36c",
      "constituentKey": "d11bedcf-0da7-4048-96dd-d074afdfa9ce",
      "parentKey": 8306649,
      "parent": "Rapistrum",
      "scientificName": "Rapistrum rugosum Coss., 1753",
      "canonicalName": "Rapistrum rugosum",
      "authorship": "Coss., 1753",
      "nameType": "SCIENTIFIC",
      "rank": "SPECIES",
      "origin": "SOURCE",
      "taxonomicStatus": "DOUBTFUL",
      "nomenclaturalStatus": [],
      "remarks": "Possible variant of Rapistrum rugosum (L.) All.",
      "numDescendants": 0,
      "lastCrawled": "2021-03-03T06:32:33.335+0000",
      "lastInterpreted": "2021-03-03T06:23:02.442+0000",
      "issues": [
        "ORTHOGRAPHIC_VARIANT"
      ],
      "synonym": false,
      "class": "Magnoliopsida"
    }
  ]
}
```

the top entry with taxonomicStatus=ACCEPTED has the vernacularName "ball-turnip", but the [web site](https://www.gbif.org/species/5373368) shows "bastard cabbage"

**Comment by jnothman** [comment]
The alternative GBIF API that gives vernacular names [shows several](https://api.gbif.org/v1/species/search?q=rapistrum%20rugosum&datasetKey=d7dddbf4-2cf0-4f39-9b2a-bb099caae36c) including:
```
Bastard Cabbage
turnipweed
ball-turnip
common giant mustard
rapistrum-weed
wild turnip
bastard-cabbage
giant mustard
annual bastardcabbage
annual bastard cabbage
bastard cabbage
grenade
red mustard
turnip weed
```
I don't understand what logic there might be for them choosing a single vernacular name in the previous API, and why that logic differs from what's shown in the web browser.

**Comment by geezacoleman** [comment]
That is very strange - Rapistrum rugosum is definitely turnipweed, wild turnip as one example in that list is a range of things but most likely Brassica rapa. Bastard cabbage is Rapistrum rugosum according to [texas invasives database](https://texasinvasives.org/plant_database/detail.php?symbol=RARU) but WSSA is turnipweed (without the space). In the weed science community WSSA is the accepted common term so preferably would go by that. How possible is it to grab the common name from (WSSA)[http://wssa.net/wssa/weed/composite-list-of-weeds/] and then the taxonomy from GBIF?

**Comment by jnothman** [comment]
The main issue with that is that the WSSA list is not something I'd really want to download on the client side, so it involves more development to put it on the backend... We could do it client side for now, but it's an excess 700kb download...

**Comment by geezacoleman** [comment]
Ah I see - if the GBIF name wasn't so strange I would be comfortable staying with that, but based in its output for turnipweed I think the best option currently is to leave off the common name entirely and stick with scientific only.

**Comment by jnothman** [comment]
This is a bit heavy on the client side, since it downloads a large list of vernacular names, but now it uses the WSSA naming when available.

**Comment by geezacoleman** [comment]
That's great! What happens if a weed is not in that database? (unlikely but possible)

**Comment by jnothman** [comment]
It falls back to gbif
________________________________

**Review by jnothman — COMMENTED** [review]
Any big issues with the code here, @ElevnLi?

**Comment by jnothman** [comment]
Merging this to make it easier to fix in master

**Pull request merged**
