### PR TITLE
Add function to reindex existing repository entry

### PR DESCRIPTION
**Pull request by jnothman**
Used manually after updating metadata schema in #336

### CODE REVIEW

**Comment by jnothman** [comment]
Can currently run this in the django shell to reindex:
```
from weedid.models import Dataset
from weedid.tasks import reindex_dataset
for uid in Dataset.objects.filter(status="C").values_list("upload_id", flat=True):
    print(uid)
    reindex_dataset(uid, process_thumbnails=False)
```

**Comment by jnothman** [comment]
Problem here is that if reindexing fails, `status` is set to "F", which means that the above code can't be reapplied
...

**Comment by jnothman** [comment]
Maybe, then, this is better:
```
import time
import os
from weedid.tasks import reindex_dataset
for uid in os.listdir("repository"):
    print(uid)
    reindex_dataset(uid, process_thumbnails=False)
    time.sleep(10)  # try to allow ES some time to reindex
```

**Comment by jnothman** [comment]
That snippet needs fixing. it should only apply to approved datasets. Maybe we need an indication of approval in the repository.

**Comment by jnothman** [comment]
I think this is closer to the goal

```py
import time
import os
from weedid.tasks import reindex_dataset
from weedid.models import Dataset

for uid in Dataset.objects.filter(status="C").values_list("upload_id", flat=True):
    if not os.path.isdir(os.path.join("repository", uid))
    print('Reindexing', uid)
    reindex_dataset(uid, process_thumbnails=True)
    time.sleep(10)  # try to allow ES some time to reindex
```

**Review by jnothman — COMMENTED** [review]
Another issue here is that this can affect upload status, and it shouldn't.

**Comment by ElevnLi** [comment]
Screen Shot 2021-03-19 at 12 10 36 pm

**Comment by jnothman** [comment]
If there are lots of datasets, will it still be possible to "select all" and reindex?

**Comment by ElevnLi** [comment]
> If there are lots of datasets, will it still be possible to "select all" and reindex?

We can add a [search_field](https://docs.djangoproject.com/en/3.1/ref/contrib/admin/#django.contrib.admin.ModelAdmin.search_fields) for status. Select all is already functional.

**Comment by jnothman** [comment]
yes, selecting to reindex all complete would be helpful. Still might be useful to have a button that shortcuts that use case.

**Comment by jnothman** [comment]
LGTM

**Pull request merged**
