### PR TITLE
Task to back up and version repo with DVC

### PR DESCRIPTION
**Pull request by jnothman**
This is towards a generic solution to repository versioning.

I don't think DVC is a very good fit. I'd consider OCFL since it's designed for similar research object contexts, and gives clear version numbers.

The question now is when this should be called, whether on a schedule, after each deposit, or both.

This also does not currently archive database info.

Ideally we would also ensure execution doesn't happen concurrently.

### CODE REVIEW

**Comment by jnothman** [comment]
This is now working and ready for review

**Review by ElevnLi — APPROVED** [review]
If it's working in production, LGTM

**Comment by jnothman** [comment]
Currently getting complaint about "stale file handle" that requires celery container to be recreated :(

Options include:
* Mount CIFS directly as a docker volume per https://stackoverflow.com/a/67036046/1017546
* Mount a non-SMB path on the host (or a docker volume) and rsync regularly to RDS

**Comment by jnothman** [comment]
While I preferred the first option, I've found myself stuck trying to use a docker volume creation statement. I kept getting `invalid argument` from kernel `mount`.

**Pull request merged**
