### PR TITLE
Show sample of images on Dataset page

### LINKED ISSUE #389: Add OG tags for facebook/twitter dataset sharing
See https://ogp.me/

Especially, add a thumbnail example as the `og:image`. This might require selecting a thumbnail from the dataset and (ideally one with at least one annotation) as an example and making the thumbnail URL available to the frontend in dataset_summary.js.

### PR DESCRIPTION
**Pull request by jnothman**
This also:
* factors a lot of the reactivesearch code, including the result
  card, out of reactive_search.js and into Components/search/
* gets rid of the datasetNames API lookup since dataset_name is now
  stored in ES
* marks one of the image thumbnails as the og:image, which fixes #389

This is not strictly in the current scope of works but I think is a
valuable UX improvement, as well as a code cleanup.

Here's what the dataset page now looks like

image

Good by you, @geezacoleman? @ElevnLi please review for code quality.

### CODE REVIEW

**Comment by jnothman** [comment]
(Note that full weed names will be shown)

**Comment by ElevnLi** [comment]
Looks good to me

**Comment by jnothman** [comment]
deployed. Check it out, @geezacoleman: https://weed-ai.sydney.edu.au/datasets/3c363da3-6274-45e4-a0ce-b307cb0f89cc

**Comment by geezacoleman** [comment]
Looks really good! Thanks @ElevnLi @jnothman

**Comment by hlydecker** [comment]
Nice work team! this looks great

**Pull request merged**
