### PR TITLE
Refactor upload stepper

### PR DESCRIPTION
**Pull request by ElevnLi**

### CODE REVIEW

**Review by jnothman — COMMENTED** [review]
The code looks good... it would be excellent to test with a mock server, or with cypress for e2e.

**Comment by jnothman** [comment]
Other uses of activeStep with absolute indices need updating, including

https://github.com/Sydney-Informatics-Hub/Weed-AI/blob/b9b5f9e54b79ce672eba2365ff8a36937f298134/search/src/Components/upload/upload_stepper.js#L217-L225

and

https://github.com/Sydney-Informatics-Hub/Weed-AI/blob/b9b5f9e54b79ce672eba2365ff8a36937f298134/search/src/Components/upload/upload_stepper.js#L309-L312

**Review by jnothman — CHANGES_REQUESTED** [review]
See previous comment about other areas needing updating to avoid indexing.

**Comment by jnothman** [comment]
To keep diffs clean, I'm going to merge this, and open another issue for the remainder of the refactor.

**Comment by jnothman** [comment]
Or do you want to wait for the non-regression testing in cypress before we merge??

**Comment by ElevnLi** [comment]
> Or do you want to wait for the non-regression testing in cypress before we merge??

Both are ok, maybe merge this first and cypress can work on testing this part as well

**Pull request merged**
