### PR TITLE
Validate category as scientific name and expand category

### LINKED ISSUE #85: Expand categories from taxonomy when indexing images
E.g. expand "crop: avena sativa" to "crop: grasses" and "crop".

### PR DESCRIPTION
**Pull request by jnothman**
Validates (only on the backend) that a category or crop type includes a valid scientific name, and expands category names through the taxonomy.

(Also fixes validation of dates with missing portions)

Fixes #85 
After indexing we should change the reactivesearch component's field from `annotation__category__name.keyword` to `annotation__category__taxo_names.keyword`

### CODE REVIEW

**Comment by jnothman** [comment]
This validates that the user has entered a correct scientific name.

**Comment by jnothman** [comment]
To roll out the labelling of weed species family, we should start by updating celery to this version, and reindexing all datasets.  Would you be able to do that @ElevnLi, to demonstrate the functionality of labelling grasses/non-grasses?

**Comment by ElevnLi** [comment]
> To roll out the labelling of weed species family, we should start by updating celery to this version, and reindexing all datasets. Would you be able to do that @ElevnLi, to demonstrate the functionality of labelling grasses/non-grasses?

Yeah, do you mean by rebuilding docker image and reindexing from admin portal? I can do it.

**Comment by jnothman** [comment]
> Yeah, do you mean by rebuilding docker image and reindexing from admin portal? I can do it.

Yes, please

**Comment by ElevnLi** [comment]
I reindexed it in production. It works but the admin portal static files seem broken.

**Comment by jnothman** [comment]
> admin portal static files

Which files are those??

**Comment by jnothman** [comment]
What's the error?

**Comment by ElevnLi** [comment]
Screen Shot 2021-05-21 at 2 02 58 pm

**Comment by jnothman** [comment]
Is the error that the stylesheets are broken??

**Comment by jnothman** [comment]
Ah, right, that's what you said above. Forgot.

**Comment by jnothman** [comment]
I'm not convinced that the reindexing worked if that branch was in place in prod, since there is no `taxo_names` field present in the indexed records.

**Comment by jnothman** [comment]
Did you make sure to rebuild celery?

**Comment by ElevnLi** [comment]
> Did you make sure to rebuild celery?

I did so, but I don't know what it is supposed to show and why it's killing the static files

**Comment by jnothman** [comment]
> > Did you make sure to rebuild celery?
> I did so, but I don't know what it is supposed to show and why it's killing the static files

It doesn't look like it to me, since it's using an old weedcoco without mention of taxo_names in indexer.py

**Comment by jnothman** [comment]
This is complete and awaits review, @ElevnLi

**Review by ElevnLi — APPROVED** [review]
LGTM

**Pull request merged**
