### PR TITLE
Fix issue where meta editor resulted in infinite recursion

### PR DESCRIPTION
**Pull request by jnothman**
Issue was due to the implementation of ConstRenderer, which did not correctly imploy 'effects'

The other changes in this PR are not essential.

A remaining issue after this fix is the slow responsiveness when entering text in the form, I think due to the upload/editor button..?

### CODE REVIEW

**Comment by ElevnLi** [comment]
This fix doesn't work when upload a metadata json. Fields from json cannot be applied to the form from my end.

**Comment by jnothman** [comment]
so this seems to work in the standalone editor, but in the uploader we've got two issues:
* can't type in the metadata form. Seems to have been introduced in 0c9a7d9b
* can't set the metadata form from the uploader UI. This appears to pre-date 0c9a7d9b

**Comment by jnothman** [comment]
The last commit appears to fix both issues on my side.

**Comment by ElevnLi** [comment]
> The last commit appears to fix both issues on my side.

Can we merge this?

**Pull request merged**
