### PR TITLE
Show weed species on result card instead of just 'weed' or 'crop'

### LINKED ISSUE #349: weed species should be shown in resultcard
The current tooltip is too hidden

### PR DESCRIPTION
**Pull request by jnothman**
Fixes #349

### CODE REVIEW

**Comment by jnothman** [comment]
I'd like to have this live before the TCG meeting tomorrow as it makes more sense of the live data.

**Comment by jnothman** [comment]
maybe I'll just deploy it?

**Comment by jnothman** [comment]
Grr the change to app.js wasn't meant to be committed

**Comment by jnothman** [comment]
I've made this live on prod.

**Comment by jnothman** [comment]
image

**Comment by geezacoleman** [comment]
very nice! Looks good.

**Pull request merged**
