### PR TITLE
Improve display of citation data on dataset summary

### LINKED ISSUE #353: Citation not appearing on datasets summary page

### PR DESCRIPTION
**Pull request by jnothman**
Fixes #353

image

(By default the Citation and Licensing accordion is closed.)

### CODE REVIEW

**Review by ElevnLi — APPROVED** [review]

**Comment by jnothman** [comment]
I want to check with @geezacoleman that the automatically generated citations are acceptable too.

**Comment by jnothman** [comment]
Thanks for review @ElevnLi

**Comment by geezacoleman** [comment]
Will the auto generated citation include the DOI if provided? If so, it seems to fit the current standards of dataset citation provided elsewhere (e.g. https://guides.lib.umich.edu/c.php?g=282964&p=3285995)

**Comment by jnothman** [comment]
Yes, it will choose the first "Identifier" URI which is usually DOI but falls back to a weed-ai URL.

**Comment by jnothman** [comment]
(But it would be nice if we had short form URLs...)

**Comment by geezacoleman** [comment]
Ok neat - I think that looks fine then. Shorter URLs would be nice but that works fine currently.

**Pull request merged**
